# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bc1367aee8c2a47234408b15c089acbf6ff0e44407950c6a74bcde39679eb837e1e88f23f6023e18428a57ba6c457893ca2b8cf82b33af50194b00211841ba9

test:
  secret_key_base: 58df894ea12bfee5299ad27ba10a767781277736f5c83313131a5e35cd9e4bb03c696a4494e90ea20ad903c7329264158175737d9ee1a95645eec218fe473d57

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 8d412aee3ceaa494fe1c276f5f7e524b9e33f649c03690e689e5b36a0cf4ce2a6f50024bc31f276c22b668e619d61a42b79f5e595759f377a8fa373e2907f41e 
